### ISSUE TITLE
Research digital certification process for adding a new user into the system

### ISSUE THREAD

**Issue by ebenissan** [DZhangLab/HIDe-infrastructure#12]
To determine verifier registration process—user should be able to add verifier. Will need to generate artificial member IDs that have verifier permissions to test the code.

**Comment by konoikon** [comment]
# Fabric Client Application Flow

![Image](https://user-images.githubusercontent.com/22823085/193355121-6c56fd44-8fe0-423a-b726-cd20abdd54b8.png)

# Overview

Upon the creation of an organization, a trusted certificate authority is defined. The CA issues credentials for users and registers them to the MSP. (The MSP is set up in the network configuration).

In order to connect to the gateway, you need to provide the wallet path (where the private key is stored), the user ID and the MSP (Membership Service Provider) that will verify registration and rights.

Then you specify the channel and chaincode ID and you can submit transactions.

# Enrolling & Registering a User

```tsx
const secret = await caClient.register({
    affiliation,
    enrollmentID: userId,
    role: 'client',
}, adminUser);
const enrollment = await caClient.enroll({
    enrollmentID: userId,
    enrollmentSecret: secret,
});
const x509Identity = {
    credentials: {
        certificate: enrollment.certificate,
        privateKey: enrollment.key.toBytes(),
    },
    mspId: orgMspId,
    type: 'X.509',
};
await wallet.put(userId, x509Identity);
```

1. Register the user to the CA
    1. affiliation is a string like `org1.department1`
    2. userId is a username, a string like `org1user`, `konoikon`, `danazhang` (Research different types of user IDs we can use, minimize the different identifiers per user).
    3. Must use an admin to register a new user
2. Enroll the user
    1. Use the username and the registration secret
3. Create an identity object and store it on the wallet

# Connecting to the Gateway

```tsx

const ccp = buildCCPOrg1(); // Loads the organization configuration
const gateway = new Gateway();

const gatewayOpts: GatewayOptions = {
    wallet,
    identity: org1UserId,
    discovery: { enabled: true, asLocalhost: true },
};

await gateway.connect(ccp, gatewayOpts);

const network = await gateway.getNetwork(channelName);

const contract = network.getContract(chaincodeName);
```

# Resources

- [https://hyperledger-fabric.readthedocs.io/en/release-2.2/developapps/wallet.html](https://hyperledger-fabric.readthedocs.io/en/release-2.2/developapps/wallet.html)
- [https://hyperledger-fabric.readthedocs.io/en/release-2.2/glossary.html#membership-services](https://hyperledger-fabric.readthedocs.io/en/release-2.2/glossary.html#membership-services)
- [https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/application-typescript/src/utils/CAUtil.ts](https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/application-typescript/src/utils/CAUtil.ts)
- [https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/application-typescript/src/app.ts](https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/application-typescript/src/app.ts)
