### ISSUE TITLE
Develop network using default template (non-production level)

### ISSUE THREAD

**Issue by ebenissan** [DZhangLab/HIDe-infrastructure#14]
- [ ] Verify the configuration of each docker container, e.g.,  how many peers nodes vs peer organizations

**Comment by i1uxaermakov** [comment]
_From https://hyperledger-fabric.readthedocs.io/en/release-2.2/test_network.html_
Each node and user that interacts with a Fabric network needs to belong to an organization in order to participate in the network. The test network includes two peer organizations, Org1 and Org2. It also includes a single orderer organization that maintains the ordering service of the network.

Every peer in the network needs to belong to an organization. In the test network, each organization operates one peer each, peer0.org1.example.com and peer0.org2.example.com.

**Comment by i1uxaermakov** [comment]
[] 4 different peers, 2 peers per organization
[] what are different ports for?

**Comment by i1uxaermakov** [comment]
What are the ports used for?

Peer ports
- CORE_PEER_LISTENADDRESS=0.0.0.0:9051
- CORE_OPERATIONS_LISTENADDRESS=peer0.org2.example.com:9445

Ordered ports
- ORDERER_GENERAL_LISTENPORT=7050
- ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
- ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443

**Comment by i1uxaermakov** [comment]
Have been understanding the shell scripts and the docker-compose files to understand how the network is brought up.
- found out how to create a new organization
- found an article that describes how to add a peer: https://kctheservant.medium.com/add-a-peer-to-an-organization-in-test-network-hyperledger-fabric-v2-2-4a08cb901c98

Overall, the process involves the following:
- generating certificates and other cryptographic materials for the new peer using the CA of the organization we are adding the node for (scripts are available)
- Create configuration for the new peer and bring up the container (need to modify default files like docker-compose.yaml)
- Add the new peer to the channel that peer1 and peer2 share (common ledger)
- if any chaincode was installed on other peers, it has to be installed on this one too. Without the chaincode the peer cannot be queried
